n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro: '))
s = n1 + n2
m = n1 * n2
d = n1 / n2
di = n1 // n2
e = n1 ** n2
print('A soma é {},\nA multiplicação é {},\nA divisão é {:.3f},\nA divisão inteira é {},\nA potência é {}.' .format(s, m, d, di, e), end='____________')
print('(5 x n1 x n2) = {}' .format(5*n1*n2))
